# This file was auto-generated by the framework. You can add data models or change the existing ones

from moose_lib import Key, moose_data_model
from dataclasses import dataclass
from datetime import datetime
from typing import Optional

# This decorator is used to mark the data model as a Moose data model
@moose_data_model
@dataclass
class Foo:
    primary_key: Key[str]
    timestamp: float
    optional_text: Optional[str]

@moose_data_model
@dataclass
class Bar:
    primary_key: Key[str]
    utc_timestamp: datetime
    has_text: bool
    text_length: int
